networks:
  cardgame-network:
    driver: bridge

services:
  cardgame-db:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    networks:
      - cardgame-network

  cardgame-api:
    build:
      context: ./
    container_name: cardgame-api
    depends_on:
      - 'cardgame-db'
    ports:
      - "8080:8080"
    networks:
      - cardgame-network
    environment:
      DB_HOST: cardgame-db
      DB_USERNAME: root
      DB_PASSWORD: ""
      PROFILE_ACTIVE: dev
