version: "3.9"

networks:
  cardgame-network:
    driver: bridge

services:
  cardgame-db:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    networks:
      - cardgame-network
